// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../../components/plasmic/copy_of_halcyon_studios/PlasmicGlobalContextsProvider";
import { UnnamedGlobalGroupOfVariantsContext } from "../../components/plasmic/copy_of_halcyon_studios/PlasmicGlobalVariant__UnnamedGlobalGroupOfVariants";
import { PlasmicBuy, Head } from "../../components/plasmic/copy_of_halcyon_studios/PlasmicBuy";

export { Head };

function Buy({ location, path, params }) {
  React.useEffect(() => {
    // Inject the script here
    (function () {
      // Set tenant name here
      var TENANT_NAME = 'halcyonstudio';

      var d = document;
      var sA = ['polyfills', 'js'];

      for (var i = 0; i < sA.length; i++) {
        var s = d.createElement('script');
        s.src = 'https://' + TENANT_NAME + '.marianaiframes.com/' + sA[i];
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
      }
    })();
  }, []);

  return (
    <UnnamedGlobalGroupOfVariantsContext.Provider value={undefined}>
      <GlobalContextsProvider>
        <PageParamsProvider__
          route={path}
          params={params}
          query={Object.fromEntries(new URLSearchParams(location.search))}
        >
          <PlasmicBuy />
        </PageParamsProvider__>
      </GlobalContextsProvider>
      <noscript>
        Please enable JavaScript to view the
        <a href="https://marianatek.com/?ref_noscript" rel="nofollow">
          Web Integrations by Mariana Tek.
        </a>
      </noscript>
    </UnnamedGlobalGroupOfVariantsContext.Provider>
  );
}

export default Buy;
